version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  foodgram:
    container_name: foodgram
    image: lexlibman/foodgram:latest
    restart: always
    volumes:
      - static_data:/code/static
      - media_data:/code/media
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.19.6-alpine
    restart: always
    volumes:
      - static_data:/code/static
      - media_data:/code/media
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - foodgram
    env_file:
      - ./.env